name: "Deploy website"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: print bun version
        run: bun --version
      - name: install dependencies
        run: bun install --frozen-lockfile
      - name: build
        run: bunx --bun astro build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/rewrite'
    steps:
      - name: build
        run: BASE="/staging/" bunx --bun astro build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          target-folder: staging
